name: CI Pipeline

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests
        run: |
          if [ -f "./run_tests.sh" ]; then
            bash ./run_tests.sh
          elif [ -f "package.json" ]; then
            npm install
            npm test
          elif [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
            pytest
          else
            echo "No test command found."
            exit 1
          fi

      - name: Build Docker image
        run: docker build -t my-app:latest .
